export const infoConfig = [
  {
    id: "twitter-handle",
    inputConfig: {
      name: "twitter_handle",
      elementType: "input",
      errorMsg: "",
      isValid: false,
      value: "",
      inputType: "text",
      minLength: 8,
      placeHolder: "Twitter Handle",
      description: "INFO",
    },
  },
  {
    id: "discord-url",
    inputConfig: {
      name: "discord_url",
      elementType: "input",
      errorMsg: "",
      isValid: false,
      value: "",
      inputType: "text",
      minLength: null,
      placeHolder: "Discord Server URL",
    },
  },
  {
    id: "telegram-handle",
    inputConfig: {
      name: "telegram_handle",
      elementType: "input",
      errorMsg: "",
      isValid: false,
      value: "",
      inputType: "text",
      minLength: 8,
      placeHolder: "Telgram handle",
    },
  },
  {
    id: "ens-domain",
    inputConfig: {
      name: "ens_domain",
      elementType: "input",
      errorMsg: "",
      isValid: false,
      value: "",
      inputType: "text",
      minLength: 8,
      placeHolder: "ENS domain",
      description: "ADDITIONAL (OPTIONAL)",
    },
  },
];
